version: 2

models:

    - name: sales
      description: Store information for each product
      tests:
        - unique:
            column_name: "(orders_id || '-' || products_id)"
            
      columns:
          - name: orders_id
            description: identifier of the order
            tests : 
            - not_null 

          - name: products_id
            description: identifier of the product
            tests : 
            - not_null 

          - name: qty
            description: the number of product in each order

          - name: turnover
            description: total benifit
            tests : 
            - not_null 

          - name: purchase_cost
            description: cost of order
            tests : 
            - not_null 

          - name: margin
            description: turnover-purchase_cost